// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"JHE_admin/internal/handler/apihandler"
	"JHE_admin/internal/handler/authorityhandler"
	"JHE_admin/internal/handler/autocodehandler"
	"JHE_admin/internal/handler/basehandler"
	"JHE_admin/internal/handler/casbinhandler"
	"JHE_admin/internal/handler/excelhandler"
	"JHE_admin/internal/handler/feedbackhandler"
	"JHE_admin/internal/handler/filehandler"
	"JHE_admin/internal/handler/menuhandler"
	"JHE_admin/internal/handler/simpleuploadhandler"
	sysdictionaryhandler "JHE_admin/internal/handler/sysdictionary"
	"JHE_admin/internal/handler/sysdictionarydetailhandler"
	"JHE_admin/internal/handler/sysoperationrecordhandler"
	"JHE_admin/internal/handler/systemhandler"
	"JHE_admin/internal/handler/customerhandler"
	"JHE_admin/internal/handler/userhandler"
	"JHE_admin/internal/handler/billhandler"
	"JHE_admin/internal/svc"
	"net/http"
	"strings"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	basehandler.RegisterHandlersAutocode(engine, serverCtx)
	userhandler.RegisterHandlersAutocode(engine, serverCtx)
	menuhandler.RegisterHandlersAutocode(engine, serverCtx)
	apihandler.RegisterHandlersAutocode(engine, serverCtx)
	systemhandler.RegisterHandlersAutocode(engine, serverCtx)
	casbinhandler.RegisterHandlersAutocode(engine, serverCtx)
	autocodehandler.RegisterHandlersAutocode(engine, serverCtx)
	authorityhandler.RegisterHandlersAutocode(engine, serverCtx)
	sysdictionaryhandler.RegisterHandlersAutocode(engine, serverCtx)
	sysoperationrecordhandler.RegisterHandlersAutocode(engine, serverCtx)
	sysdictionarydetailhandler.RegisterHandlersAutocode(engine, serverCtx)
	filehandler.RegisterHandlersAutocode(engine, serverCtx)
	excelhandler.RegisterHandlersAutocode(engine, serverCtx)
	simpleuploadhandler.RegisterHandlersAutocode(engine, serverCtx)
	customerhandler.RegisterHandlersAutocode(engine, serverCtx)
	customerhandler.RegisterHandlersAutocode1(engine, serverCtx)
	// equipmenthandler.RegisterHandlersAutocode(engine, serverCtx)
	// driveschoolhandler.RegisterHandlersAutocode(engine, serverCtx)
	feedbackhandler.RegisterHandlersAutocode(engine, serverCtx)
	billhandler.RegisterHandlersAutocode(engine, serverCtx)
	dirlevel := []string{":1", ":2", ":3", ":4", ":5", ":6", ":7", ":8", ":9", ":10", ":11", ":12", ":13", ":14", ":15"}
	patern := "/resource/"
	dirpath := "./resource/"
	for i := 1; i < len(dirlevel); i++ {
		path := "/" + strings.Join(dirlevel[:i], "/")
		//最后生成 /asset
		engine.AddRoute(
			rest.Route{
				Method:  http.MethodGet,
				Path:    path,
				Handler: dirhandler(patern, dirpath),
			})
	}

}
func Filehandler(filepath string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		http.ServeFile(w, r, filepath)
	}
}
func dirhandler(patern, filedir string) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		handler := http.StripPrefix(patern, http.FileServer(http.Dir(filedir)))
		handler.ServeHTTP(w, req)
	}
}
